### ISSUE TITLE
Add active state indicator for selected workspace in menu

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspace-picker#12]
checkmark to show active workspace

![image](https://user-images.githubusercontent.com/46250921/132878142-782b8fb0-0ddc-46b2-854a-a432dd978c5f.png)

**Comment by GitMurf** [comment]
I believe it starts by highlighting the active workspace... is that not enough? Would you like something "clearer"?

**Comment by jsmorabito** [comment]
> I believe it starts by highlighting the active workspace... is that not enough? Would you like something "clearer"?

Oh interesting I didn't notice it was doing that (which is part of the issue 😅)...it would be more easily discoverable with a checkmark or other indicator. The checkmark seems to be the convention rn in analogous menus 
![image](https://user-images.githubusercontent.com/46250921/132880384-c7cc5d42-b311-4802-8de7-6a236b78ffc5.png)

**Comment by GitMurf** [comment]
Yep I don't disagree with you... or at minimum should try to figure out how to make the "highlight" of the current active workspace more noticeable. But I also like your idea because as soon as you press an arrow key or type something then the highlighted item changes and now you lose the signifier of which is the current workspace. So now that I think about it I would love a checkbox like you suggested!

**Comment by jsmorabito** [comment]
implemented in 0.0.8
